In [62]:
list1 = [1,2,3,4,5]
#run: ctrl+ enter
#run and open new cell alt+enter

In [64]:
print("ctrl+enter")

ctrl+enter


# heading

In [2]:
print(list1)
print(type(list1))

[1, 2, 3, 4, 5]
<class 'list'>


In [46]:
import numpy as np

In [4]:
n=np.array(list1)
print(n)

[1 2 3 4 5]


In [9]:
print(type(n))

<class 'numpy.ndarray'>


In [11]:
p=10
q=20
r=p+q
print(r)

30


In [12]:
l1=[1,2,3,4,5]
l2=[6,7,8,9,10]
l3=l1+l2
print(l3)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [13]:
 
lt1 = [5, 10, 15, 20, 25, 30]  
lt2 = [2, 4, 6, 8, 10, 12]  
  
 
print ( " Python Original list 1: " + str (lt1))  
print ( "Python Original list 2: " + str (lt2))  
  

res_lt = [] 
for x in range (0, len (lt1)):  
    res_lt.append( lt1[x] + lt2[x])  
  
 
print ( " Addition of the list lt1 and lt2 is: " + str (res_lt))  

 Python Original list 1: [5, 10, 15, 20, 25, 30]
Python Original list 2: [2, 4, 6, 8, 10, 12]
 Addition of the list lt1 and lt2 is: [7, 14, 21, 28, 35, 42]


In [47]:
a=np.array([2,4,6,8,10])
b=np.array([1,3,5,7,9])
c=a+b
print(c)
print(type(c))

d=a-b
print(d)

[ 3  7 11 15 19]
<class 'numpy.ndarray'>
[1 1 1 1 1]


In [16]:
print(a*b)

[ 2 12 30 56 90]


In [17]:
print(a/b)

[2.         1.33333333 1.2        1.14285714 1.11111111]


In [48]:
print(a**2)

[  4  16  36  64 100]


In [49]:
print(b*5)

[ 5 15 25 35 45]


In [19]:
test_1 = np.array([92, 94, 88, 91, 87])
test_2 = np.array([79, 100, 86, 93, 91])
test_3 = np.array([87, 85, 72, 90, 92])


test_3_fixed=test_3+2
total_grade = test_1+test_2+test_3_fixed
final_grade = total_grade/3
print(final_grade)

[86.66666667 93.66666667 82.66666667 92.         90.66666667]


#indexing & Slicing

In [50]:
combined = np.array([[92, 94, 88, 91, 87],
                    [79, 100, 86, 93, 91],
                    [87, 85, 72, 90, 92]])
print(combined)

[[ 92  94  88  91  87]
 [ 79 100  86  93  91]
 [ 87  85  72  90  92]]


In [51]:
combined[0][3]#row,column

91

In [29]:
combined[1:3,3:5] #[rowstart:rowend,colstart:colend]

array([[93, 91],
       [90, 92]])

In [30]:
#row,Column
#start:end , start:end
print(combined[0:3,2:4])


[[88 91]
 [86 93]
 [72 90]]


In [22]:
combined[0]

array([92, 94, 88, 91, 87])

In [23]:
combined[0][2]

88

In [24]:
combined[0:2]

array([[ 92,  94,  88,  91,  87],
       [ 79, 100,  86,  93,  91]])

In [25]:
combined[0:2,0:2]#start:end.. upto end : end is not inclusive

array([[ 92,  94],
       [ 79, 100]])

In [35]:
combined[1,2]

86

In [27]:
combined[1,1]

100

In [36]:
combined[2,2]

72

In [39]:
combined[:,3]

array([91, 93, 90])

In [40]:
#celcius to farenit
cvalues=[23.4,25.6,28.9,23.6]

#using list operations
fvalues=[]
for x in cvalues:
    fvalues.append(x*9/5+32)
    
print(fvalues)

[74.12, 78.08, 84.02, 74.48]


In [52]:
#using ndarray
cvalues=[23.4,25.6,28.9,23.6]
c=np.array(cvalues)
f=c*9/5+32
print(f)

[74.12 78.08 84.02 74.48]


In [55]:
# i1==int8
#i2==int16
#i4==int32
#i8==int64

dt2=np.dtype(np.int64)
print(dt2)


print("-------------------------------------------------")
dt=np.dtype(np.int32)
print(dt)
print("----------------------------")

dt=np.dtype('i8')
print(dt)
print("----------------------------")

dt=np.dtype('i2')
print(dt)
print("----------------------------")



int64
-------------------------------------------------
int32
----------------------------
int64
----------------------------
int16
----------------------------


In [59]:
# first create data stucture
#[]
#variable=np.dtype(['variable_name',datatype])
dt=np.dtype([('age',np.int8)])
print(dt)



[('age', 'i1')]


In [72]:
# now apply nd array object

a=np.array([(10,),(20,),(30,),(45,)],dtype=dt)
print(a)


[(10,) (20,) (30,) (45,)]


In [61]:

# array name can be use to access content

print(a['age'])

[10 20 30 45]


# logical/conditional operations on ndarray

In [75]:
array1 = np.array([11,45,78,89,67.5,78,100])
print(array1)

[ 11.   45.   78.   89.   67.5  78.  100. ]


In [69]:
print(array1>50)

[False False  True  True  True  True  True]


In [76]:
print(array1[array1>50])

[ 78.   89.   67.5  78.  100. ]


In [77]:
print(array1[(array1>50) & (array1<80)])

[78.  67.5 78. ]


In [78]:
#array[(condition1) &/| (condition2)]

In [79]:
porridge = np.array([79, 65, 50, 63, 56, 90, 85, 98, 79, 51])
cold = porridge[porridge < 60]

hot = porridge[porridge > 80]

just_right = porridge[(porridge >= 60) & (porridge <= 80)]

print(cold)
print(hot)
print(just_right)

[50 56 51]
[90 85 98]
[79 65 63 79]


In [81]:
a=np.zeros(5,dtype=int)
print(a)

[0 0 0 0 0]


In [83]:
b=np.ones(5,dtype=int)
print(b)

[1 1 1 1 1]


In [87]:
e=np.empty((3,2))#(row,col)
print(e)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [91]:
p=np.arange(11,21,2) #start,end,interval/step
print(p)

[11 13 15 17 19]


In [92]:
a=np.array([-1.7,1.5,-0.2,0.6,10])


# After the river in your town flooded during a recent hurricane, you've become interested in collecting data about the its height. Every day for the past month, you walk to the river, measure the height of the water, and enter this information into a notebook

In [93]:
water_height = np.array([4.01, 4.03, 4.27, 4.29, 4.19,
                         4.15, 4.16, 4.23, 4.29, 4.19,
                         4.00, 4.22, 4.25, 4.19, 4.10,
                         4.14, 4.03, 4.23, 4.08, 14.20,
                         14.03, 11.20, 8.19, 6.18, 4.04,
                         4.08, 4.11, 4.23, 3.99, 4.23])

In [94]:
#to find the average water height:
avg=np.mean(water_height)
print(avg)


5.251


In [95]:
#sort our data to see if there could be any measurements to throw our data
srt=np.sort(water_height)
print(srt)


[ 3.99  4.    4.01  4.03  4.03  4.04  4.08  4.08  4.1   4.11  4.14  4.15
  4.16  4.19  4.19  4.19  4.22  4.23  4.23  4.23  4.23  4.25  4.27  4.29
  4.29  6.18  8.19 11.2  14.03 14.2 ]


In [97]:
#measure the median to see if its more representative of the dataset
#median tells us where half of our data lies
med=np.median(water_height)
print(med)

4.19


In [103]:
per=np.percentile(water_height,67)
print(per)

4.23


In [98]:

#standard deviation to understand how similar or 
#how different each data point is
dev=np.std(water_height)
print(dev)

2.784585367099861


In [1]:
import numpy as np

In [2]:
#3D array : number of array, rows,columns
#2 arrays, 3 rows, 4 columns
a=np.zeros((2,3,4))
print(a)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [3]:
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [4]:
newarr = arr.reshape(4,3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [5]:
na = arr.reshape(6,2)
print(na)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


In [6]:
newthree = arr.reshape(2,3,2)
print(newthree)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [7]:
n = np.array([[1,2,3],[4,5,6]])
print(n)

[[1 2 3]
 [4 5 6]]


In [10]:
f = n.reshape(-1)
print(f)

[1 2 3 4 5 6]


In [13]:
a=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [12]:
print(a.shape)

(3, 3)


In [15]:
a.shape=(3,4)
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [23]:
a=np.arange(24)
print(a.itemsize)

4


In [18]:
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [19]:
print(a.ndim)


1


In [20]:
print(a.reshape(4,2,3))

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]]]


In [21]:
print(a.itemsize)

4


In [25]:
student= np.dtype([('name','S20'),('age','i1'),('marks','f4')])

a= np.array([('Pratik',21,70),('Prasad',18,75)],dtype=student)
print(a.itemsize)

25


In [26]:
x=np.array([1,2,3,4,5])
print(x)

[1 2 3 4 5]


In [27]:
print(x.flags)

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False



In [28]:
x.flags['WRITEABLE']=True

In [29]:
x[2]=10
print(x)

[ 1  2 10  4  5]


In [30]:
x.flags['WRITEABLE']=False

In [31]:
x[2]=3
print(x)

ValueError: assignment destination is read-only

In [9]:
a=np.array([10,20,30])
b=np.array([3,5,7])

print("first array")
print(a)
print("second array")
print(b)
print("first array")
print(np.mod(a,b))

first array
[10 20 30]
second array
[3 5 7]
first array
[1 0 2]


In [33]:
calorie_stats = np.genfromtxt("cereal.csv",delimiter=",")
calorie_stats

array([ 70., 120.,  70.,  50., 110., 110., 110., 130.,  90.,  90., 120.,
       110., 120., 110., 110., 110., 100., 110., 110., 110., 100., 110.,
       100., 100., 110., 110., 100., 120., 120., 110., 100., 110., 100.,
       110., 120., 120., 110., 110., 110., 140., 110., 100., 110., 100.,
       150., 150., 160., 100., 120., 140.,  90., 130., 120., 100.,  50.,
        50., 100., 100., 120., 100.,  90., 110., 110.,  80.,  90.,  90.,
       110., 110.,  90., 110., 140., 100., 110., 110., 100., 100., 110.])

In [40]:
p=np.array([1.0,5.55,123,0.567,25.337])
print(np.around(p))
c=np.count(p)
c

[  1.   6. 123.   1.  25.]


AttributeError: module 'numpy' has no attribute 'count'

In [35]:
print(np.ceil(p))
print(np.floor(p))

[  1.   6. 123.   1.  26.]
[  1.   5. 123.   0.  25.]


In [36]:
a=np.array([10,20,30])
b=np.array([5,10,15])

s=np.add(a,b)
s

array([15, 30, 45])

In [37]:
d=np.subtract(a,b)
print(d)
e=np.multiply(a,b)
print(e)
div=np.divide(a,b)
print(div)


[ 5 10 15]
[ 50 200 450]
[2. 2. 2.]


In [38]:
a=np.array([10,20,30])
b=np.array([3,5,7])
m=np.mod(a,b)
m

array([1, 0, 2], dtype=int32)

In [39]:
sqr=np.power(a,2)
sqr

array([100, 400, 900], dtype=int32)

In [44]:
a1=np.arange(100)
print(a1[a1 % 2 == 0])

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48 50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94
 96 98]


In [45]:
print(a1[a1 % 2 != 0])

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95
 97 99]
